##Importing Libraries

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
df = pd.read_csv("wine_data.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

##Separating Features and Dependent Variable

In [14]:
X = df.drop('quality', axis = 1)
y = df['quality']

print(X)
print(y)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

##Train test split

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [16]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
140             8.4             0.745         0.11             1.9      0.090   
1232            7.6             0.430         0.29             2.1      0.075   
720             8.4             0.560         0.04             2.0      0.082   
77              6.8             0.785         0.00             2.4      0.104   
39              7.3             0.450         0.36             5.9      0.074   
...             ...               ...          ...             ...        ...   
763             9.3             0.655         0.26             2.0      0.096   
835             7.6             0.665         0.10             1.5      0.066   
1216            7.9             0.570         0.31             2.0      0.079   
559            13.0             0.470         0.49             4.3      0.085   
684             9.8             0.980         0.32             2.3      0.078   

      free sulfur dioxide  

##Scaling Data

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
print(X_train)
print(X_test)

[[ 0.03570115  1.17013908 -0.82797173 ... -0.77068411  0.91195248
  -0.75660071]
 [-0.42519441 -0.54734879  0.09751438 ...  0.59078753 -0.10608706
  -0.85048089]
 [ 0.03570115  0.16145573 -1.18788299 ... -0.57618817 -1.2372421
  -0.75660071]
 ...
 [-0.25235857  0.21597915  0.20034617 ... -0.12236428  0.1767017
  -0.85048089]
 [ 2.68585058 -0.32925509  1.12583228 ... -0.0575323   0.12014395
   2.15368509]
 [ 0.84226836  2.45143956  0.25176207 ... -0.38169222 -1.01101109
  -0.94436108]]
[[ 1.41838781 -0.32925509  0.81733691 ... -0.90034808  0.57260597
   0.36996154]
 [-0.13713469  1.57906477 -1.39354657 ...  0.3314596  -0.72822233
  -0.75660071]
 [ 0.43898476 -1.31067673  0.30317796 ... -0.31686023  1.02506798
   1.21488322]
 ...
 [-0.59803024 -0.90175105  1.12583228 ...  0.3314596   0.68572147
   0.55772191]
 [ 4.18376113  0.84299854  2.51406145 ... -2.3266517   0.12014395
   0.74548229]
 [-0.42519441 -0.54734879  0.09751438 ...  0.59078753 -0.10608706
  -0.85048089]]


##Training Random Forest Model

In [19]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

##Comparing predicted vs original values

In [20]:
y_pred = rf.predict(X_test)
print(y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.values.reshape(len(y_test), 1)), axis=1))

[6 5 7 5 5 6 5 6 5 5 5 5 6 7 5 7 7 5 5 5 6 5 6 6 6 5 5 6 5 6 6 6 6 6 7 7 5
 5 6 6 5 7 7 7 6 5 5 6 5 6 5 5 6 6 5 5 5 5 7 5 5 5 6 6 5 6 5 5 7 6 5 5 5 5
 6 6 5 5 5 7 6 5 6 6 6 5 5 5 5 5 5 6 6 5 7 5 6 5 5 5 7 7 6 7 6 5 6 6 6 5 6
 5 7 5 5 6 6 7 6 6 5 6 5 5 6 7 5 5 5 6 5 5 6 6 6 5 6 6 7 5 6 5 5 5 5 6 7 6
 5 5 5 5 6 5 6 6 6 5 6 7 5 6 7 5 5 5 6 6 6 6 6 6 5 7 5 6 7 7 7 5 5 6 6 6 6
 5 5 6 5 6 6 5 5 6 5 5 5 5 5 5 5 6 6 6 6 5 5 6 6 6 6 6 5 7 5 6 5 7 6 5 5 5
 6 6 6 6 6 6 6 6 5 6 5 6 7 6 6 7 7 6 5 6 5 5 6 5 5 5 5 5 5 5 5 6 5 6 5 5 5
 6 6 6 6 6 5 5 5 5 6 5 4 5 5 6 6 6 6 6 6 7 5 7 5 6 6 5 5 5 7 5 5 4 6 5 5 6
 6 6 5 5 6 5 6 5 6 6 5 5 5 5 5 6 5 5 5 6 6 7 5 7 5 5 7 7 6 5 7 6 5 5 7 5 5
 6 5 6 7 5 5 6 5 5 5 6 6 5 6 6 5 6 5 6 5 5 6 5 6 5 6 7 5 5 5 6 6 5 5 7 5 5
 6 5 5 6 5 5 5 6 6 6 6 6 5 5 5 6 5 6 6 6 6 5 5 7 6 6 5 5 5 5]
[[6 6]
 [5 5]
 [7 7]
 [5 6]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [5 4]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [7 5]
 [5 6]
 [7 6]
 [7 7]
 [5 5]
 [5 5]
 [5 4]
 [6 7]
 [5 6]
 [6 6]
 [6 4]
 [6 6]
 [5 5]
 [5 5]

##Confusion Matrix and Accuracy score

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   2   0   0]
 [  0   0  10   4   0   0]
 [  0   0 136  29   4   0]
 [  0   2  45 108  15   0]
 [  0   0   3  15  22   0]
 [  0   0   0   1   4   0]]


0.665